authentication/urls.py
from django.urls import path
from .views import (
    LoginView,
    register_validator,
    RegisterView,
    logout_view
    )

app_name = 'auth'
urlpatterns = [
    path('login', LoginView.as_view(), name = 'login'),
    path('logout', logout_view, name = 'logout'),
    path('register', RegisterView.as_view(), name = 'register'),
    path('register/register-validator', register_validator, name = 'field_validator'),
]

core/urls.py
from django.urls import path
from .views import home_view, financial_summary

app_name = 'core'
urlpatterns = [
    path('', home_view, name = 'home'),
    path('dashboard-endpoint/', financial_summary , name = 'financial_summary')
]

expenses/urls.py
from django.urls import path
from .views import (
    ExpensesView,
    CreateExpensesView, 
    EditExpensesView, 
    delete_view,
    search_view,
    add_category, 
    expense_category_summary_endpoint
    )

app_name = "exp"
urlpatterns = [
    path("", ExpensesView.as_view(), name = "expenses"),
    path("create", CreateExpensesView.as_view(), name = "create"),
    path("edit/<int:id>", EditExpensesView.as_view(), name = "edit"),
    path("delete/", delete_view, name = "delete"),
    path("search/", search_view, name = "search"),
    path("add-category/", add_category, name = "add_category"),
    path("expense-category-summary-endpoint/", expense_category_summary_endpoint, name = "expense_category_summary"),
]

expenses_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = "core")),
    path('auth/', include('authentication.urls', namespace = "auth")),
    path('preferences/', include('user_preferences.urls', namespace = "pref")),
    path('expenses/', include('expenses.urls', namespace = "exp")),
    path('income/', include('income.urls', namespace = "inc")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

income/urls.py
from django.urls import path
from .views import (
    IncomeView,
    CreateIncomeView, 
    EditIncomeView, 
    delete_view,
    search_view, 
    income_endpoint
    )

app_name = "inc"
urlpatterns = [
    path("", IncomeView.as_view(), name = "income"),
    path("create", CreateIncomeView.as_view(), name = "create"),
    path("edit/<int:id>", EditIncomeView.as_view(), name = "edit"),
    path("delete/", delete_view, name = "delete"),
    path("search/", search_view, name = "search"),

    path("income-endpoint/", income_endpoint, name = "income_endpoint"),
]

user_preferences/urls.py
from django.urls import path
from .views import Index

app_name = "pref"
urlpatterns = [
    path('', Index.as_view(), name = "index")
]

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="text-center container-fluid alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} mt-2  alert-dismissible  fade show " role="alert">
            <strong class="message">{{message}}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

templates/partials/modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method = 'post'>
            {% csrf_token %}
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">Category:</label>
              <input name = "name" type="text" class="form-control" id="recipient-name">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" id ="add-category" class="btn btn-primary">Add</button>
        </div>
      </div>
    </div>
</div>

<script>
  $(document).ready(()=>{
    $('#add-category').click(function(e){
      const messagesContainer = $('#MessagesContainer')
      e.preventDefault()
      const value = $('input[name=name]').val()
      const csrf_token = $('input[name=csrfmiddlewaretoken]').val()
      $.ajax({
        type : 'post', 
        url : "{% url 'exp:add_category' %}", 
        data : {
          'csrfmiddlewaretoken' : csrf_token,
          'name' : value
        },
        success : (response) => {
          $('#exampleModal').modal('hide')
          if (response.response_template){    
            $('#CatgoryContainer').html(response.response_template)
          }
          if(response.msg){
            messagesContainer.html(response.msg)
          }
        }
      })
    })
  })
</script>

templates/partials/navbar.html
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
        {% if user.is_authenticated %}
            {{user.username}}
        {% else %}
            Wellcome
        {% endif %}
    </a>
    <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
    <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
        {% if user.is_authenticated %}
            <a 
            id = "logout"
            class="nav-link" 
            href="{% url 'auth:logout' %}">
                Sign out
            </a>
        {% else %}
            <a class="nav-link" href="{% url 'auth:login' %}">Sign in</a>
        {% endif %}
    </li>
    </ul>
</nav>
<script>
    $('#logout').click((e) => {
        e.preventDefault()
        Swal.fire({
                title: 'Are you sure?',
                text: 'do you wish to log out',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#343a40',
                cancelButtonColor: '#d9534f',
                confirmButtonText: 'Yes please!'
            }).then((result)=>{
                if (result.isConfirmed) {
                    $.ajax({
                        url : "{% url 'auth:logout' %}",
                        type: 'post',
                        data : {
                            'csrfmiddlewaretoken' : "{{csrf_token}}",
                            'response' : 'yes',
                            'ajax' : true
                        },
                        success : (response)=> {
                            window.location.replace('http://127.0.0.1:8000' + response.url)
                        }
                    })
                }
            })
    })
</script>

templates/partials/paginator.html
<div class="d-flex justify-content-between w-100 align-items-center">
    <p>
        page {{queryset.number}} of {{queryset.paginator.num_pages}}
    </p>
    <ul class="pagination">
        {% if not queryset.number == 1 %}
        <li class="page-item">
            <a class="btn btn-outline-primary py-1 px-3 mr-2" href="?page=1">&#60;&#60;1</a>
        </li>
        {% endif %}
        {% if queryset.has_previous %}
        <li class="btn btn-outline-primary py-1 px-3 mr-2">
            <a class="" href="?page={{queryset.previous_page_number}}" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% if queryset.has_next %}
        <li class="page-item">
            <a class="btn btn-outline-primary py-1 px-3" href="?page={{queryset.next_page_number}}">Next</a>
        </li>
        {% endif %}
        {% if not queryset.number == queryset.paginator.num_pages %}
        <li class="page-item">
            <a class="btn btn-outline-primary py-1 px-3 ml-2" href="?page={{queryset.end_index}}">{{queryset.end_index}} &#62;&#62;</a>
        </li>
        {% endif %}
    </ul>
</div>

templates/partials/sidebar.html
<div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'core:home' %}">
          <span data-feather="home"></span>
          Dashboard <span class="sr-only">(current)</span>
        </a> 
      </li>
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Expenses</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'exp:expenses' %}">
          <span data-feather="file-text"></span>
          Expense Summary
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inc:income' %}">
          <span data-feather="file-text"></span>
          Income Summary
        </a>
      </li>
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pref:index'  %}">
          <span data-feather="file-text"></span>
          General
        </a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'pref:index'  %}">
          <span data-feather="file-text"></span>
          Account
        </a>
      </li> -->
    </ul>
  </div>