core/urls.py
from django.urls import path
from .views import home_view, financial_summary

app_name = 'core'
urlpatterns = [
    path('', home_view, name = 'home'),
    path('dashboard-endpoint/', financial_summary , name = 'financial_summary')
]

expenses_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = "core")),
    path('auth/', include('authentication.urls', namespace = "auth")),
    path('preferences/', include('user_preferences.urls', namespace = "pref")),
    path('expenses/', include('expenses.urls', namespace = "exp")),
    path('income/', include('income.urls', namespace = "inc")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

income/urls.py
from django.urls import path
from .views import (
    IncomeView,
    CreateIncomeView, 
    EditIncomeView, 
    delete_view,
    search_view, 
    income_endpoint
    )

app_name = "inc"
urlpatterns = [
    path("", IncomeView.as_view(), name = "income"),
    path("create", CreateIncomeView.as_view(), name = "create"),
    path("edit/<int:id>", EditIncomeView.as_view(), name = "edit"),
    path("delete/", delete_view, name = "delete"),
    path("search/", search_view, name = "search"),

    path("income-endpoint/", income_endpoint, name = "income_endpoint"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from expenses.models import Expenses
from income.models import Income
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import datetime

@login_required
def home_view(request):
    date_now = datetime.date.today()
    today = date_now - datetime.timedelta(hours = 24)
    prev_month = date_now - datetime.timedelta(days = 31)
    prev_week = date_now - datetime.timedelta(days = 7)
    prev_year = date_now - datetime.timedelta(days = 365)

    def get_summary(time):
        income = Income.objects.time_amount_filter(time)
        expense = Expenses.objects.time_amount_filter(time)
        total_amount = income['amount'] - expense['amount']
        total_transactional_count = income['queryset'].count() + expense['queryset'].count()
        return {
            'amount' : total_amount,
            'count' : total_transactional_count
        }
    
    todays_summary = get_summary(today)
    prev_week_summary =  get_summary(prev_week)
    prev_month_summary =  get_summary(prev_month)
    prev_year_summary =  get_summary(prev_year)

    context = {
        'todays_summary' : todays_summary,
        'prev_week_summary' : prev_week_summary,
        'prev_month_summary' : prev_month_summary,
        'prev_year_summary' : prev_year_summary,
    }
    return render(request, 'core/home.html', context)


@login_required
def financial_summary(request):
    date_now = datetime.date.today()
    
    def get_amount(prev, date_now):
        amount = 0
        income_qs = Income.objects.filter(date__gte = prev, date__lte = date_now)
        expense_qs = Expenses.objects.filter(date__gte = prev, date__lte = date_now)

        for item in income_qs:
            amount += item.amount
        for item in expense_qs:
            amount -= item.amount
        return amount

    def get_prev_week(date_now):
        days_of_the_week = {
            1 : 'Tuesday' ,
            2 : 'Wednesday' ,
            3 : 'Thursday' ,
            4 : 'Friday',
            5 : 'Saturday',
            6 : 'Sunday',
            0 : 'Monday',
        }

        today = datetime.date.today().weekday()
        prev_week_analysis = {}
        for i in range(1, 8):
            prev_day = date_now - datetime.timedelta(days = 1)
            prev_week_analysis[days_of_the_week[today]] = get_amount(prev_day, date_now)
            date_now = prev_day
            today = date_now.weekday()

        return prev_week_analysis

    def get_prev_year(date_now):
        # for the past year
        current_month = datetime.datetime.now().month
        month_name = datetime.datetime.strptime(str(current_month), "%m").strftime('%B')
        prev_month_analysis = {}
        
        for i in range(12):
            prev_month = date_now - datetime.timedelta(days = 30)
            prev_month_analysis[month_name] = get_amount(prev_month, date_now)
            date_now = prev_month
            current_month = date_now.month
            month_name = datetime.datetime.strptime(str(current_month), "%m").strftime('%B') 

        return prev_month_analysis


    
    data = {
        'prev_week_analysis' : get_prev_week(date_now),
        'prev_month_analysis' : get_prev_year(date_now),
    }
    return JsonResponse(data)

templates/core/home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block content %}
<div class="row w-100">
    <nav aria-label="breadcrumb " class="mb-2 bg-light w-100 d-flex justify-content-between flex-row">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" href = "{% url 'core:home' %}">
                    dashboard
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current = "page" >
                <a class="" href = "#">
                    financial summary
                </a>
            </li>
        </ol>
        <div class="d-flex align-items-center">
            <form class="" action="" method = 'get' >
                <div class="input-group">
                    <input  class = "form-control" 
                            id = "IncomeSearch"
                            name = "query" 
                            type = "search" 
                            placeholder = "search"/>

                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fa-solid fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
            <a href = "{% url 'inc:create' %}" class="btn btn-outline-dark m-2"><i class="fa-solid fa-plus"></i></a>
        </div>
    </nav>
    <div class="w-100 row income-card-container justify-content-between mb-5">
        <div class="col-md-3" >
            <div class="border border-primary rounded p-4 income-card" style="height:200px;">
                <div class=" d-flex justify-content-between income-card-title">
                    <h5 class="text-dark">Today</h5>
                    <div class="bg-dark text-justify pt-1 text-light text-center rounded" style="width:50px; height: 30px;">
                        {{todays_summary.count}}
                    </div>
                </div>
                <div class="text-dark income-card-footer">({{user.user_preference.currency}}) {{todays_summary.amount|intcomma}}</div>
            </div>
        </div>
        <div class="col-md-3" >
            <div class="bg-info rounded p-4 income-card" style="height:200px;">
                <div class=" d-flex justify-content-between income-card-title">
                    <h5 class="text-light">This Week</h5>
                    <div class="bg-light text-justify pt-1 text-center rounded" style="width:50px; height: 30px;">
                        {{prev_week_summary.count}}
                    </div>
                </div>
                <div class="text-light income-card-footer">({{user.user_preference.currency}}) {{prev_week_summary.amount|intcomma}}</div>
            </div>
        </div>
        <div class="col-md-3" >
            <div class="bg-success rounded p-4 income-card" style="height:200px;">
                <div class=" d-flex justify-content-between income-card-title">
                    <h5 class="text-light">This Month</h5>
                    <div class="bg-light text-justify pt-1 text-center rounded" style="width:50px; height: 30px;">
                        {{prev_month_summary.count}}
                    </div>
                </div>
                <div class="text-light income-card-footer">({{user.user_preference.currency}}) {{prev_month_summary.amount|intcomma}}</div>
            </div>
        </div>
        <div class="col-md-3 pr-0" >
            <div class="bg-primary rounded p-4 income-card" style="height:200px;">
                <div class=" d-flex justify-content-between income-card-title">
                    <h5 class="text-light">This Year</h5>
                    <div class="bg-light text-justify pt-1 text-center rounded" style="width:50px; height: 30px;">
                        {{prev_year_summary.count}}
                    </div>
                </div>
                <div class="text-light income-card-footer">({{user.user_preference.currency}}) {{prev_year_summary.amount|intcomma}}</div>
            </div>
        </div>
    </div>
    <div id = "ChartContainer" class="w-100">
        <h3 class="text-center w-100 mt-2 mb-3 ">Analysis</h3>
        <div class="row w-100 justify-content-around inverted-indicator">
            <div class="col-5 bg-light shadow-sm p-3" >
                <canvas id="First" width="400" height="400"></canvas>
                <h3 class="text-center no-data d-none w-100" id = "FirstNoData">No transactions the past Week</h3>
            </div>
            <div class="col-5 bg-light shadow-sm p-3">
                <canvas id="Second" width="400" height="400"></canvas> 
                <h3 class="text-center no-data d-none w-100" id = "SecondNoData">No transactions the past Year</h3>
            </div>
        </div>
        <div class="d-flex w-100 justify-content-center">
            <div class = "indicator m-5"></div>
        </div>
    </div>
</div>
{% endblock content %}
{% block extrascript %}
<script src="{% static 'Js/chart-dashboard.js' %}"></script>
{% endblock extrascript %}