core/urls.py
from django.urls import path
from .views import home_view, financial_summary

app_name = 'core'
urlpatterns = [
    path('', home_view, name = 'home'),
    path('dashboard-endpoint/', financial_summary , name = 'financial_summary')
]

expenses_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = "core")),
    path('auth/', include('authentication.urls', namespace = "auth")),
    path('preferences/', include('user_preferences.urls', namespace = "pref")),
    path('expenses/', include('expenses.urls', namespace = "exp")),
    path('income/', include('income.urls', namespace = "inc")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

income/urls.py
from django.urls import path
from .views import (
    IncomeView,
    CreateIncomeView, 
    EditIncomeView, 
    delete_view,
    search_view, 
    income_endpoint
    )

app_name = "inc"
urlpatterns = [
    path("", IncomeView.as_view(), name = "income"),
    path("create", CreateIncomeView.as_view(), name = "create"),
    path("edit/<int:id>", EditIncomeView.as_view(), name = "edit"),
    path("delete/", delete_view, name = "delete"),
    path("search/", search_view, name = "search"),

    path("income-endpoint/", income_endpoint, name = "income_endpoint"),
]

income/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
import datetime
class IncomeManager(models.Manager):
    def search(self, query=None):
        if query is None or query == "" or len(query) < 1:
            return self.get_queryset(), True

        results = self.get_queryset().filter(
            Q(amount__startswith = query) |
            Q(date__startswith = query) |
            Q(description__icontains = query) |
            Q(source__icontains = query) 
        )
        return results, False
    def time_amount_filter(self, time):
        '''
            This returns a qs filtered by the time provided, as well as the total amount 
        '''
        amount = 0
        date_now = datetime.date.today()
        result = self.get_queryset().filter(
            date__gte = time, 
            date__lte = date_now
        )
        for item in result:
            amount += item.amount 

        return {
            'queryset' : result ,
            'amount' : amount
        }

class Income(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)
    source = models.CharField(max_length = 150)

    objects = IncomeManager()
    class Meta:
        verbose_name_plural = "Income"
        ordering = ['-date']

    def __str__(self):
        return self.owner.username

# class Category(models.Model):
#     name = models.CharField(max_length = 50)

#     class Meta:
#         verbose_name_plural = 'Categories'

#     def __str__(self):
#         return self.name

income/forms.py
from django import forms
from .models import Income
class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = [
            'amount',
            'description',
            'date',
            'source',
        ]

income/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views import View
from .forms import IncomeForm
from .models import Income
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from expenses.utils import paginate_qs
import datetime
from django.template.loader import render_to_string
from expenses.utils import render_to_json

PAGINATE_BY = 5
class IncomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        income_qs = Income.objects.filter(owner = request.user)
        paginator_obj = paginate_qs(request, income_qs, PAGINATE_BY)
        context = {
            'queryset' : paginator_obj, 
        }
        return render(request, 'income/income.html', context)

class CreateIncomeView(LoginRequiredMixin,View):
    def get_context(self):
        context = {}
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context()
        return render(request, 'income/income_form.html', context)    

    def post(self, request, *args, **kwargs):
        initial_data = request.POST 
        form = IncomeForm(request.POST or None, initial = initial_data)
        if form.is_valid():
            form_instance = form.save(commit = False)
            form_instance.owner = request.user
            form_instance.save()
            messages.success(request, 'Income Added')
            return redirect('inc:income')
            
        messages.error(request, 'Invalid Form')
        context = self.get_context()   
        context['form'] = form
        
        return render(request, 'income/income_form.html', context) 

class EditIncomeView(View):
    def get_context(self):
        context = {}
        return context
    def get_income_obj(self, id):
        try :
            income_instance = Income.objects.get(id = id, owner = self.request.user)
        except ObjectDoesNotExist as e:
            messages.error(request, "Sorry, this income does not exist")
            return redirect('/')

        return income_instance

    def get(self, request, *args, **kwargs):
        context = self.get_context()
        id = kwargs['id']
        income_instance = self.get_income_obj(id)
        form = IncomeForm(instance = income_instance)
        context['form'] = form
        return render(request, 'income/income_form.html', context)

    def post(self, request, *args, **kwargs):
        id = kwargs['id']
        income_instance = self.get_income_obj(id)
        form = IncomeForm(request.POST or None, instance = income_instance)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated successfully")
            return redirect('inc:income')
        messages.error(request, "Invalid form")
        context = self.get_context()
        context['form'] = form  
        return render(request, 'income/income_form.html', context)


def delete_view(request, id=None):
    try:
        if not id:
            id = request.POST['id']
        income_obj = Income.objects.get(id = id, owner = request.user)
    except ObjectDoesNotExist as e:
        messages.error(request, "Sorry, this Income does not exist")
        return redirect('/')

    if request.POST:
        income_obj.delete()
        messages.success(request, "Income deleted")
    queryset = Income.objects.filter(owner = request.user)
    context = {
        'queryset' : queryset
    }
    data = {
            'msg' : render_to_string('partials/messages.html', {}, request), 
            'is_deleted' : True
        }
    
    return render_to_json(request, data)
    # return render(request, 'partials/income/income_table_inline.html', context)


def search_view(request):
    query = request.GET.get('query')
    #NOTE is_empty flags when the search bar has nothing in it
    queryset, is_empty = Income.objects.search(query)
    context = {
        'queryset' : queryset
    }
    template_name = "income/search_result.html"
    if request.is_ajax:
        template_name = 'partials/income/income_table_inline.html'
        if is_empty:
            queryset = paginate_qs(request, queryset, PAGINATE_BY)
            context['queryset'] = queryset
    return render(request, template_name, context)


@login_required
def income_endpoint(request):
    date_now = datetime.date.today()
    
    def get_amount(prev, date_now):
        amount = 0
        qs = Income.objects.filter(date__gte = prev, date__lte = date_now)
        for item in qs:
            amount += item.amount
        return amount

    def get_prev_week(date_now):
        days_of_the_week = {
            1 : 'Tuesday' ,
            2 : 'Wednesday' ,
            3 : 'Thursday' ,
            4 : 'Friday',
            5 : 'Saturday',
            6 : 'Sunday',
            0 : 'Monday',
        }

        today = datetime.date.today().weekday()
        prev_week_analysis = {}
        for i in range(1, 8):
            prev_day = date_now - datetime.timedelta(days = 1)
            prev_week_analysis[days_of_the_week[today]] = get_amount(prev_day, date_now)
            date_now = prev_day
            today = date_now.weekday()

        return prev_week_analysis

    def get_prev_year(date_now):
        # for the past year
        current_month = datetime.datetime.now().month
        month_name = datetime.datetime.strptime(str(current_month), "%m").strftime('%B')
        prev_month_analysis = {}
        
        for i in range(12):
            prev_month = date_now - datetime.timedelta(days = 30)
            prev_month_analysis[month_name] = get_amount(prev_month, date_now)
            date_now = prev_month
            current_month = date_now.month
            month_name = datetime.datetime.strptime(str(current_month), "%m").strftime('%B') 

        return prev_month_analysis


    
    data = {
        'prev_week_analysis' : get_prev_week(date_now),
        'prev_month_analysis' : get_prev_year(date_now),
    }
    return JsonResponse(data)

templates/income/income.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row w-100">
    <nav aria-label="breadcrumb " class="mb-2 bg-light w-100 d-flex justify-content-between flex-row">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" href = "{% url 'inc:income' %}">
                    Income
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current = "page" >
                <a class="" href = "#">
                    My Income
                </a>
            </li>
        </ol>
        <div class="d-flex align-items-center">
            <form class="" action="" method = 'get' >
                <div class="input-group">
                    <input  hx-get = "{% url 'inc:search' %}" 
                            hx-target = "#search-swap" 
                            hx-trigger = "keyup changed delay:200ms"
                            class = "form-control" 
                            id = "IncomeSearch"
                            name = "query" 
                            type = "search" 
                            placeholder = "search"/>

                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fa-solid fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
            <a href = "{% url 'inc:create' %}" class="btn btn-outline-dark m-2"><i class="fa-solid fa-plus"></i></a>
        </div>
    </nav>
    {% if queryset %}
        <div id = "search-swap" class="w-100">
        {% include 'partials/income/income_table_inline.html' %}
        </div>
        <div id = "ChartContainer" class="w-100">
            <h3 class="text-center w-100 mt-2 mb-3 ">Analysis</h3>
            <div class="row w-100 justify-content-around inverted-indicator">
                <div class="col-5 bg-light shadow-sm p-3" >
                    <canvas id="First" width="400" height="400"></canvas>
                    <h3 class="text-center no-data d-none w-100" id = "FirstNoData">No Income the past Week</h3>
                </div>
                <div class="col-5 bg-light shadow-sm p-3">
                    <canvas id="Second" width="400" height="400"></canvas> 
                    <h3 class="text-center no-data d-none w-100" id = "SecondNoData">No Income the past Year</h3>
                </div>
            </div>
            <div class="d-flex w-100 justify-content-center">
                <div class = "indicator m-5"></div>
            </div>
        </div>
    {% else %}
        <div class="col-12 mt-5">
        <h2 class="text-center w-100">No income</h2>
        </div>
    {% endif %}
</div>
{% endblock content %}
{% block extrascript %}
<script src="{% static 'Js/chart-income.js' %}"></script>
{% endblock extrascript %}

templates/income/income_form.html
{% extends 'base.html' %}
{% block content %}
<div class="row w-100">
    <div class="col-md-12">
        <form class = "shadow-sm" id = "form" method="post">
            <div id ="MessagesContainer">
                {% include 'partials/messages.html' %}
            </div>
            {% csrf_token %}
                <div class="text-center mb-3">
                    {% if form.instance %}
                    <h3 class="mb-2">Edit Income</h3>
                    {% else %}
                    <h3 class="mb-2">Add Income</h3>
                    {% endif %}
                </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <div class="form-outline d-flex flex-column mb-4">
                        <input  type="number" 
                                id="amount_id" 
                                class="form-control"  
                                name = "amount" 
                                placeholder="Enter Amount"
                                {% if form.instance  %}
                                value = "{{form.instance.amount}}"
                                {% endif %}
                            />
                        
                        {% if form.amount.errors %}
                        <div class="invalid-feedback d-block text-center">
                            {{form.amount.errors}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-outline d-flex flex-column mb-4">
                        <input  type="text" 
                                id="amount_id" 
                                class="form-control"  
                                name = "source" 
                                placeholder="Source of Income"
                                {% if form.instance  %}
                                value = "{{form.instance.source}}"
                                {% endif %}
                            />
                        
                        {% if form.source.errors %}
                        <div class="invalid-feedback d-block text-center">
                            {{form.source.errors}}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            
            
            <div class="form-outline d-flex flex-column mb-4">
                <textarea   rows = '6'
                            placeholder="Description(optional)"
                            type="text" 
                            id="description_id" 
                            class="form-control"  
                            name = "description">{% if form.instance  %}{{form.instance.description}}{% endif %}</textarea>
                {% if form.description.errors %}
                <div class="invalid-feedback d-block text-center">
                    {{form.description.errors}}
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="form-group col-4">
                    <input class="form-control" 
                            type="date" 
                            name = "date"
                            {% if form.instance  %}
                            value = "{{form.instance.date|date:'Y-m-d'}}"
                            {% endif %}>
                </div>
            </div>
            {% if form.date.errors %}
            <div class="invalid-feedback d-block text-center">
                {{form.date.errors}}
            </div>
            {% endif %}
            <!-- Submit button -->
            <button type="submit" id = "submit_btn" class="btn btn-primary w-25 m-auto mb-3">Save</button>
        </form>
    </div>
</div>
{% endblock content %}