core/urls.py
from django.urls import path
from .views import home_view, financial_summary

app_name = 'core'
urlpatterns = [
    path('', home_view, name = 'home'),
    path('dashboard-endpoint/', financial_summary , name = 'financial_summary')
]

expenses/urls.py
from django.urls import path
from .views import (
    ExpensesView,
    CreateExpensesView, 
    EditExpensesView, 
    delete_view,
    search_view,
    add_category, 
    expense_category_summary_endpoint
    )

app_name = "exp"
urlpatterns = [
    path("", ExpensesView.as_view(), name = "expenses"),
    path("create", CreateExpensesView.as_view(), name = "create"),
    path("edit/<int:id>", EditExpensesView.as_view(), name = "edit"),
    path("delete/", delete_view, name = "delete"),
    path("search/", search_view, name = "search"),
    path("add-category/", add_category, name = "add_category"),
    path("expense-category-summary-endpoint/", expense_category_summary_endpoint, name = "expense_category_summary"),
]

expenses_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = "core")),
    path('auth/', include('authentication.urls', namespace = "auth")),
    path('preferences/', include('user_preferences.urls', namespace = "pref")),
    path('expenses/', include('expenses.urls', namespace = "exp")),
    path('income/', include('income.urls', namespace = "inc")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

expenses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
import datetime
from django.dispatch import receiver
from django.db.models.signals import post_save

class ExpenseManager(models.Manager):
    def search(self, query=None):
        if query is None or query == "" or len(query) < 1:
            return self.get_queryset(), True

        results = self.get_queryset().filter(
            Q(amount__startswith = query) |
            Q(date__startswith = query) |
            Q(description__icontains = query) |
            Q(category__icontains = query) 
        )
        return results, False
        
    def time_amount_filter(self, time):
        '''
            This returns a qs filtered by the time provided, as well as the total amount 
        '''
        amount = 0
        date_now = datetime.date.today()
        result = self.get_queryset().filter(
            date__gte = time, 
            date__lte = date_now
        )
        for item in result:
            amount += item.amount 

        return {
            'queryset' : result ,
            'amount' : amount
        }


class Expenses(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)
    category = models.CharField(max_length = 150)

    objects = ExpenseManager()
    class Meta:
        verbose_name_plural = "Expenses"
        ordering = ['-date']

    def __str__(self):
        return self.owner.username

class Category(models.Model):
    name = models.CharField(max_length = 50)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-id']
    def __str__(self):
        return self.name


@receiver(post_save, sender = Expenses)
def add_category(sender, instance, created, **kwargs):
    category_name = instance.category
    if not Category.objects.filter(name__iexact = category_name).exists():
        Category.objects.create(name = category_name)

# post_save.connect(add_category, sender = Expenses)

expenses/forms.py
from django import forms
from .models import Expenses, Category

class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = [
            'amount',
            'description',
            'date',
            'category',
        ]

class CreateCatgoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'name'
        ]

expenses/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.views import View
from .forms import ExpensesForm, CreateCatgoryForm
from .models import Category, Expenses
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .utils import paginate_qs, render_to_json
from django.template import RequestContext
import datetime
PAGINATE_BY = 4
class ExpensesView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        expenses_qs = Expenses.objects.filter(owner = request.user)
        paginator_obj = paginate_qs(request, expenses_qs, PAGINATE_BY)
        context = {
            'queryset' : paginator_obj
        }
        return render(request, 'expenses/expenses.html', context)

class CreateExpensesView(LoginRequiredMixin, View):
    def get_context(self):
        category = Category.objects.all()
        context = {
            'categories' : category
        }
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context()
        return render(request, 'expenses/expense_form.html', context)    

    def post(self, request, *args, **kwargs):
        initial_data = request.POST 
        form = ExpensesForm(request.POST or None, initial = initial_data)
        if form.is_valid():
            form_instance = form.save(commit = False)
            form_instance.owner = request.user
            form_instance.save()
            messages.success(request, 'Expenses Added')
            return redirect('exp:expenses')
            
        messages.error(request, 'Invalid Form')
        context = self.get_context()   
        context['form'] = form
        
        return render(request, 'expenses/expense_form.html', context)

class EditExpensesView(LoginRequiredMixin, View):
    def get_context(self):
        category = Category.objects.all()
        context = {
            'categories' : category
        }
        return context
    def get_expense_obj(self, id):
        try :
            expense_instance = Expenses.objects.get(id = id, owner = self.request.user)
        except ObjectDoesNotExist as e:
            messages.error(request, "Sorry, this expense does not exist")
            return redirect('/')

        return expense_instance

    def get(self, request, *args, **kwargs):
        context = self.get_context()
        id = kwargs['id']
        expense_instance = self.get_expense_obj(id)
        form = ExpensesForm(instance = expense_instance)
        context['form'] = form
        return render(request, 'expenses/expense_form.html', context)

    def post(self, request, *args, **kwargs):
        id = kwargs['id']
        expense_instance = self.get_expense_obj(id)
        form = ExpensesForm(request.POST or None, instance = expense_instance)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated successfully")
            return redirect('exp:expenses')
        messages.error(request, "Invalid form")
        context = self.get_context()
        context['form'] = form  
        return render(request, 'expenses/expense_form.html', context)

@login_required
def delete_view(request, id=None):
    try:
        if not id:
            id = request.POST['id']
        expense_obj = Expenses.objects.get(id = id, owner = request.user)
    except ObjectDoesNotExist as e:
        messages.error(request, "Sorry, this Expense does not exist")
        return redirect('/')

    if request.POST:
        expense_obj.delete()
        messages.success(request, "Expense deleted")
    # queryset = Expenses.objects.filter(owner = request.user)
    # context = {
    #     'queryset' : queryset
    # }
    data = {
            'msg' : render_to_string('partials/messages.html', {}, request), 
            'is_deleted' : True
        }
    
    return render_to_json(request, data)

@login_required
def search_view(request):
    query = request.GET.get('query')
    #NOTE is_empty flags when the search bar has nothing in it
    queryset, is_empty = Expenses.objects.search(query)
    context = {
        'queryset' : queryset
    }
    template_name = "expenses/search_result.html"
    if request.htmx:
        template_name = 'partials/expenses/expense_table_inline.html'
        if is_empty:
            queryset = paginate_qs(request, queryset, PAGINATE_BY)
            context['queryset'] = queryset
    return render(request, template_name, context)

@login_required
def add_category(request):
    if request.POST:
        category_qs = Category.objects.all()
        form = CreateCatgoryForm(request.POST or None)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            if not category_qs.filter(name__iexact = name).exists():
                form.save()
                messages.success(request, 'Category Added')
            else:
                messages.success(request, 'Already exists')
        else:
            messages.error(request, 'Invalid Form')
        context = {
            'categories' : category_qs,
        }
        data = {
            'msg' : render_to_string('partials/messages.html', {}, request), 
            'response_template' : render_to_string('partials/expenses/category_inline_form.html', context) 
        }
        
        return render_to_json(request, data)

@login_required
def expense_category_summary_endpoint(request):
    date_now = datetime.date.today()
    prev_month = date_now - datetime.timedelta(days = 31)
    prev_year = date_now - datetime.timedelta(days = 365)
    
    final_rep_year = {}
    final_rep_month = {}
    def get_expense_qs(prev_time):
        expenses_qs = Expenses.objects.filter(
                owner = request.user,
                date__gte = prev_time, date__lte = date_now 
            )
        return expenses_qs
    expense_qs_month = get_expense_qs(prev_month)
    expense_qs_year = get_expense_qs(prev_year)

    def get_category(expense):
        return expense.category

    
    category_list_month = list(set(map(get_category, expense_qs_month)))
    category_list_year = list(set(map(get_category, expense_qs_year)))
    
    def get_category_amount(category, queryset):
        amount = 0
        expense_cat_qs = queryset.filter(category__iexact = category )
        for expense in expense_cat_qs:
            amount += expense.amount
        return amount

    for category in category_list_month:
            final_rep_month[category] = get_category_amount(category, expense_qs_month)

    for category in category_list_year:
            final_rep_year[category] = get_category_amount(category, expense_qs_year)
    
    data = {
        'expenses_prev_month' : final_rep_month,
        'expenses_prev_year' : final_rep_year,
    }
    return JsonResponse(data)

templates/expenses/expense_form.html
{% extends 'base.html' %}
{% block content %}
<div class="row w-100">
    <div class="col-md-12">
        <div id ="MessagesContainer">
            {% include 'partials/messages.html' %}
        </div>
        <form class = "shadow-sm" id = "form" method="post">
        {% csrf_token %}
            <div class="text-center mb-3">
                {% if form.instance %}
                <h3 class="mb-2">Edit Expenses</h3>
                {% else %}
                <h3 class="mb-2">Add Expenses</h3>
                {% endif %}
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <div class="form-outline d-flex flex-column mb-4">
                        <input  type="number" 
                                id="amount_id" 
                                class="form-control"  
                                name = "amount" 
                                placeholder="Enter Amount"
                                {% if form.instance  %}
                                value = "{{form.instance.amount}}"
                                {% endif %}
                            />
                        
                        {% if form.amount.errors %}
                        <div class="invalid-feedback d-block text-center">
                            {{form.amount.errors}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class = "form-group col-md-6" id = "CatgoryContainer">
                    {% include 'partials/expenses/category_inline_form.html' %}
                </div>
            </div>

            
            
            <div class="form-outline d-flex flex-column mb-4">
                <textarea   rows = '6'
                            placeholder="Description(optional)"
                            type="text" 
                            id="description_id" 
                            class="form-control"  
                            name = "description">{% if form.instance  %}{{form.instance.description}}{% endif %}</textarea>
                {% if form.description.errors %}
                <div class="invalid-feedback d-block text-center">
                    {{form.description.errors}}
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="form-group col-4">
                    <input class="form-control" 
                            type="date" 
                            name = "date"
                            {% if form.instance  %}
                            value = "{{form.instance.date|date:'Y-m-d'}}"
                            {% endif %}>
                </div>
            </div>
            {% if form.date.errors %}
            <div class="invalid-feedback d-block text-center">
                {{form.date.errors}}
            </div>
            {% endif %}
            
            <!-- Submit button -->
            <button type="submit" id = "submit_btn" class="btn btn-primary w-25 m-auto mb-3">Save</button>
        </form>
    </div>
</div>
{% include 'partials/modal.html' %}
{% endblock content %}

templates/expenses/expenses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row w-100">
    <nav aria-label="breadcrumb " class="mb-2 bg-light w-100 d-flex justify-content-between flex-row">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="" href = "{% url 'exp:expenses' %}">
                    Expenses
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current = "page" >
                <a class="" href = "#">
                    My Expenses
                </a>
            </li>
        </ol>
        <div class="d-flex align-items-center">
            <form class="" action="" method = 'get' >
                <div class="input-group">
                    <input hx-get = "{% url 'exp:search' %}" 
                            hx-target = "#search-swap" 
                            hx-trigger = "keyup changed delay:200ms"
                            class = "form-control" 
                            name = "query" 
                            type = "search" 
                            placeholder = "search"
                            id = "Search"/>

                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fa-solid fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
            <a href = "{% url 'exp:create' %}" class="btn btn-outline-dark m-2"><i class="fa-solid fa-plus"></i></a>
        </div>
    </nav>
    
    {% if queryset %}
    <div id = "search-swap" class="w-100">
    {% include 'partials/expenses/expense_table_inline.html' %}
    </div>
    {% include 'partials/paginator.html' %}
    <div id = "ChartContainer" class="w-100">
        <h3 class="text-center w-100 mt-2 mb-3 ">Analysis</h3>
        <div class="row w-100 justify-content-around inverted-indicator">
            <div class="col-5 border border-primary p-3" >
                <canvas id="First" width="400" height="400"></canvas>
                <h3 class="text-center no-data d-none w-100" id = "FirstNoData">No Expenses the past month</h3>
            </div>
            <div class="col-5 border border-primary p-3">
                <canvas id="Second" width="400" height="400"></canvas> 
                <h3 class="text-center no-data d-none w-100" id = "SecondNoData">No Expenses the past Week</h3>
            </div>
        </div>
        <div class="d-flex w-100 justify-content-center">
            <div class = "indicator m-5"></div>
        </div>
    </div>
    {% else %}
        <div class="col-12 mt-5">
        {% include 'partials/messages.html' %}
        <h2 class="text-center w-100">No Expenses</h2>
        </div>
    {% endif %}
</div>

{% endblock content %}
{% block extrascript %}
<script src="{% static 'Js/chart-expense.js' %}"></script>
{% endblock extrascript %}